# Generated by Django 5.2.1 on 2025-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_d',
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.CharField(default='no description', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='price',
            field=models.IntegerField(default='5'),
            preserve_default=False,
        ),
    ]
